name: mentor-app
type: php:8.2

build:
  flavor: composer

dependencies:
  nodejs:
    node: 20
    npm: 10

hooks:
  build: |
    npm install
    npm run build
  deploy: |
    php artisan config:cache
    php artisan route:cache
    php artisan view:cache

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
      allow: true
      scripts: true
      index:
        - index.php

disk: 2048

mounts:
  "/storage":
    source: local
    source_path: "storage"
  "/bootstrap/cache":
    source: local
    source_path: "cache"

